platform :ios, '7.0'
inhibit_all_warnings!
use_frameworks!

target 'KSYFaceunityKitDemo' do
  pod 'Bugly'
  pod 'GPUImage',  '0.1.7'
  pod 'libksygpulive/KSYGPUResource'
  pod 'libksygpulive/libksygpulive', '1.8.7'
end
