platform :ios, '7.0'
inhibit_all_warnings!
use_frameworks!

#target 'KSYLiveDemo' do
	pod 'Bugly'
	pod 'GPUImage'
        pod 'libksygpulive/KSYGPUResource'
	pod 'libksygpulive/libksygpulive'
        #pod 'libksygpulive/libksygpulive', :git => 'https://github.com/ksvc/KSYLive_iOS.git', :tag => 'v1.8.3'
	#pod 'libksygpulive/libksygpulive', :git => 'https://github.com/ksvc/KSYLive_iOS.git', :tag => 'v1.8.4'
 	#pod 'libksygpulive/libksygpulive_265', :path => '../'
#end:

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    puts "!!!! #{target.name}"
#  end
#end
