platform :ios, '7.0'
inhibit_all_warnings!
use_frameworks!

target 'KSYSTStreamer' do
  pod 'Bugly'
  pod 'GPUImage',  '0.1.7'
  pod 'libksygpulive/KSYGPUResource'
  pod 'libksygpulive/libksygpulive', '1.9.0'
end
