platform :ios, '7.0'
inhibit_all_warnings!
use_frameworks!

target 'KSYFaceunityKitDemo' do
  pod 'Bugly'
  pod 'GPUImage',  '0.1.7'
  pod 'libksygpulive/KSYGPUResource', :git => 'git@code.csdn.net:ksvc/ksylive_ios.git', :tag => 'v1.8.7'
  pod 'libksygpulive/libksygpulive', :git => 'git@code.csdn.net:ksvc/ksylive_ios.git', :tag => 'v1.8.7'
end
